import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('drizzle/0000_workspace.sql','utf8'));const env={DB:{prepare(sql){return {bind(...args){return {async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}},async first(){return sqlite.prepare(sql).get(...args)||null}}}}}}};return {env,sqlite}}
async function call(env,body,path='/api/workspace'){const res=await worker.fetch(new Request('https://example.test'+path,body?{method:'POST',headers:{origin:'https://example.test','content-type':'application/json'},body:JSON.stringify(body)}:{}),env);return {status:res.status,data:await res.json()}}
async function approved(env){const loaded=await call(env);const r=await call(env,{action:'approve',expectedVersion:loaded.data.version,expectedFingerprint:loaded.data.quoteFingerprint});assert.equal(r.status,200);return r.data}
test('UI source has labelled keyboard controls, mobile breakpoints and reduced motion',()=>{const html=readFileSync('public-ui/index.html','utf8'),css=readFileSync('public-ui/style.css','utf8'),client=readFileSync('public-ui/client.js','utf8');assert.match(html,/Skip to workspace/);assert.match(html,/aria-labelledby="approval-title"/);assert.match(css,/@media\(max-width:500px\)/);assert.match(css,/focus-visible/);assert.match(css,/prefers-reduced-motion/);assert.match(client,/showModal\(\)/);assert.match(client,/form.reportValidity\(\)/);assert.match(client,/Your input is preserved/)});
test('workspace persists and rejects stale viewed version approval',async()=>{const {env}=fixture();const old=await call(env);assert.equal(old.status,200);await call(env,{action:'price'});const r=await call(env,{action:'approve',expectedVersion:old.data.version,expectedFingerprint:old.data.quoteFingerprint});assert.equal(r.status,409);assert.equal(r.data.code,'STALE_REVIEW');assert.equal((await call(env)).data.state.approval,null)});
test('quote fingerprint required even at current version',async()=>{const {env}=fixture();const a=await call(env);const r=await call(env,{action:'approve',expectedVersion:a.data.version,expectedFingerprint:'wrong'});assert.equal(r.status,409);assert.equal(r.data.code,'STALE_REVIEW')});
test('budget cannot be bypassed by direct approval endpoint',async()=>{const {env}=fixture();const s=await call(env);await call(env,{action:'compare',need:{...s.data.state.need,budget:100}});const r=await call(env);const blocked=await call(env,{action:'approve',expectedVersion:r.data.version,expectedFingerprint:r.data.quoteFingerprint});assert.equal(blocked.status,409);assert.equal(blocked.data.code,'POLICY_BLOCKED')});
test('lost response retry recovers one persisted receipt and one stock debit',async()=>{const {env}=fixture();const s=await approved(env),approvalId=s.state.approval.id;const first=await call(env,{action:'checkout',approvalId,loseResponse:true});assert.equal(first.status,503);assert.equal(first.data.code,'SIMULATED_TIMEOUT');const second=await call(env,{action:'checkout',approvalId,loseResponse:true});assert.equal(second.status,200);assert.equal(second.data.replayed,true);assert.equal(second.data.state.receipts.length,1);assert.equal(second.data.state.catalog[0].stock,34);const reset=await call(env,{action:'reset'});assert.equal(reset.data.state.receipts.length,1);assert.equal(reset.data.state.approval,null);assert.equal(reset.data.state.catalog[0].stock,42)});
test('concurrent checkout attempts produce a single durable order',async()=>{const {env}=fixture();const s=await approved(env);const calls=await Promise.all([call(env,{action:'checkout',approvalId:s.state.approval.id}),call(env,{action:'checkout',approvalId:s.state.approval.id})]);assert.ok(calls.some(r=>r.status===200));const loaded=await call(env);assert.equal(loaded.data.state.receipts.length,1);assert.equal(loaded.data.state.catalog[0].stock,34)});
test('stock change prevents checkout and reset clears blocked state',async()=>{const {env}=fixture();const s=await approved(env);await call(env,{action:'stock'});const r=await call(env,{action:'checkout',approvalId:s.state.approval.id});assert.equal(r.status,409);assert.equal(r.data.code,'STALE_APPROVAL');const reset=await call(env,{action:'reset'});assert.equal(reset.status,200);assert.equal(reset.data.state.approval,null)});
test('sandbox is explicitly unconfigured and browser response contains no credentials',async()=>{const {env}=fixture();const r=await call(env,{action:'create',approvalId:'no'},'/api/paypal');assert.equal(r.status,503);const data=JSON.stringify((await call(env)).data);assert.ok(!data.includes('CLIENT_SECRET'));assert.ok(!data.includes('OPENAI_API_KEY'))});
test('cross-origin writes are rejected',async()=>{const {env}=fixture();const r=await worker.fetch(new Request('https://example.test/api/workspace',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:JSON.stringify({action:'reset'})}),env);assert.equal(r.status,403)});
test('expired, definitely uncaptured sandbox order can be safely abandoned',async()=>{const {env,sqlite}=fixture();Object.assign(env,{PAYPAL_MODE:'sandbox',PAYPAL_CLIENT_ID:'fixture-id',PAYPAL_CLIENT_SECRET:'fixture-secret'});const a=await approved(env);const state=a.state;state.approval.expiresAt='2020-01-01T00:00:00Z';state.order={approvalId:state.approval.id,id:'ORDER123',createKey:'create',captureKey:'capture',startedAt:new Date().toISOString()};sqlite.prepare('UPDATE workspaces SET state=?').run(JSON.stringify(state));const original=globalThis.fetch;const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});return Response.json(url.endsWith('/token')?{access_token:'fixture-token'}:{id:'ORDER123',status:'APPROVED'})};try{const r=await call(env,{action:'abandon',approvalId:state.approval.id},'/api/paypal');assert.equal(r.status,200);assert.equal(r.data.abandoned,true);assert.equal((await call(env)).data.state.order,null);assert.ok(!calls.some(c=>c.url.endsWith('/capture')))}finally{globalThis.fetch=original}});
test('uncertain capture attempt cannot be abandoned',async()=>{const {env,sqlite}=fixture();Object.assign(env,{PAYPAL_MODE:'sandbox',PAYPAL_CLIENT_ID:'fixture-id',PAYPAL_CLIENT_SECRET:'fixture-secret'});const a=await approved(env);const state=a.state;state.order={approvalId:state.approval.id,id:'ORDER123',createKey:'create',captureKey:'capture',startedAt:new Date().toISOString(),captureStartedAt:new Date().toISOString()};sqlite.prepare('UPDATE workspaces SET state=?').run(JSON.stringify(state));const original=globalThis.fetch;globalThis.fetch=async(url)=>Response.json(url.endsWith('/token')?{access_token:'fixture-token'}:{id:'ORDER123',status:'APPROVED'});try{const r=await call(env,{action:'abandon',approvalId:state.approval.id},'/api/paypal');assert.equal(r.status,409);assert.equal(r.data.code,'RECONCILE_REQUIRED');assert.ok((await call(env)).data.state.order)}finally{globalThis.fetch=original}});
