export type Category = 'packaging' | 'office' | 'cleaning';
export type Product = { id:string; name:string; detail:string; category:Category; seller:string; price:number; stock:number; delivery:number; shipping:number; eco:boolean; revision:number };
export type Need = { text:string; category:Category; quantity:number; budget:number; delivery:number; eco:boolean; sellers:string[]; maxQuantity:number };
export type Quote = { lines:{productId:string; name:string; seller:string; quantity:number; unitPrice:number; stock:number; revision:number; delivery:number}[]; subtotal:number; shipping:number; tax:number; total:number; currency:'USD'; merchant:string };
export type Approval = {id:string; fingerprint:string; quote:Quote; createdAt:string; expiresAt:string};
export type Receipt = {id:string; approvalId:string; quote:Quote; createdAt:string; mode:'demo'|'sandbox'; captureId:string; orderId:string};
export type Audit = {id:string; at:string; event:string; detail:string};
export type Workspace = { need:Need; catalog:Product[]; selected:string; approval:Approval|null; receipts:Receipt[]; audit:Audit[]; lastReceipt:string|null; lostResponses:string[]; order:{approvalId:string; id:string|null; approveUrl?:string; createKey:string; captureKey:string; startedAt:string;captureStartedAt?:string}|null };
export class DomainError extends Error { constructor(public code:string,message:string,public status=409){super(message)} }
export const SELLERS=['Northstar Supply','Fieldwork Goods','QuickShip Depot'];
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export function initialWorkspace():Workspace{return {need:{text:'Restock packaging for 200 coffee shipments. Prefer recyclable mailers, delivered within 5 days.',category:'packaging',quantity:8,budget:30000,delivery:5,eco:true,sellers:[...SELLERS],maxQuantity:50},catalog:[
{id:'mail-kraft',name:'Kraft shipping mailers',detail:'25 mailers / pack · 10 × 13 in',category:'packaging',seller:SELLERS[0],price:2180,stock:42,delivery:3,shipping:1200,eco:true,revision:1},
{id:'mail-recycled',name:'Recycled padded mailers',detail:'25 mailers / pack · 10 × 13 in',category:'packaging',seller:SELLERS[1],price:2460,stock:18,delivery:4,shipping:0,eco:true,revision:1},
{id:'mail-express',name:'Standard poly mailers',detail:'25 mailers / pack · 10 × 13 in',category:'packaging',seller:SELLERS[2],price:1625,stock:80,delivery:2,shipping:1800,eco:false,revision:1},
{id:'mail-premium',name:'Paper cushion mailers',detail:'25 mailers / pack · 10 × 13 in',category:'packaging',seller:SELLERS[0],price:2950,stock:5,delivery:3,shipping:1200,eco:true,revision:1},
{id:'paper-recycled',name:'Recycled copy paper',detail:'500 sheets / ream · US letter',category:'office',seller:SELLERS[0],price:1280,stock:65,delivery:3,shipping:900,eco:true,revision:1},
{id:'paper-value',name:'Everyday copy paper',detail:'500 sheets / ream · US letter',category:'office',seller:SELLERS[2],price:960,stock:100,delivery:2,shipping:1500,eco:false,revision:1},
{id:'paper-premium',name:'FSC office paper',detail:'500 sheets / ream · US letter',category:'office',seller:SELLERS[1],price:1430,stock:22,delivery:4,shipping:0,eco:true,revision:1},
{id:'clean-refill',name:'Plant-based cleaner refill',detail:'1 gallon / bottle · concentrate',category:'cleaning',seller:SELLERS[1],price:2890,stock:24,delivery:4,shipping:0,eco:true,revision:1},
{id:'clean-value',name:'All-purpose cleaner',detail:'1 gallon / bottle · ready to use',category:'cleaning',seller:SELLERS[2],price:1990,stock:55,delivery:2,shipping:1500,eco:false,revision:1},
{id:'clean-pro',name:'Low-waste cleaner refill',detail:'1 gallon / bottle · concentrate',category:'cleaning',seller:SELLERS[0],price:2540,stock:32,delivery:3,shipping:1200,eco:true,revision:1},
],selected:'mail-kraft',approval:null,receipts:[],audit:[],lastReceipt:null,lostResponses:[],order:null}}
export function quoteProduct(product:Product,quantity:number):Quote{const subtotal=product.price*quantity;const shipping=subtotal>=25000?0:product.shipping;const tax=Math.round(subtotal*0.0875);return {lines:[{productId:product.id,name:product.name,seller:product.seller,quantity,unitPrice:product.price,stock:product.stock,revision:product.revision,delivery:product.delivery}],subtotal,shipping,tax,total:subtotal+shipping+tax,currency:'USD',merchant:'SupplyPilot Demo Merchant'}}
export function currentQuote(s:Workspace):Quote{const p=s.catalog.find(p=>p.id===s.selected);if(!p)throw new DomainError('NO_PRODUCT','Choose an item first.',400);return quoteProduct(p,s.need.quantity)}
export function violations(p:Product,n:Need):string[]{const q=quoteProduct(p,n.quantity);return [q.total>n.budget?'Over budget':null,p.stock<n.quantity?'Insufficient stock':null,!n.sellers.includes(p.seller)?'Seller not approved':null,p.delivery>n.delivery?'Delivery too late':null,n.eco&&!p.eco?'Recyclable / low-waste requirement not met':null,n.quantity>n.maxQuantity?'Quantity exceeds policy':null,p.category!==n.category?'Different supply category':null].filter(Boolean) as string[]}
export function ranked(s:Workspace){return s.catalog.filter(p=>p.category===s.need.category).map(p=>({product:p,quote:quoteProduct(p,s.need.quantity),issues:violations(p,s.need)})).sort((a,b)=>a.issues.length-b.issues.length||a.quote.total-b.quote.total||a.product.delivery-b.product.delivery)}
export function audit(s:Workspace,event:string,detail:string){s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),event,detail});s.audit=s.audit.slice(0,200)}
export async function fingerprint(quote:Quote){const bytes=new TextEncoder().encode(JSON.stringify(quote));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('')}
export function validateNeed(value:unknown):Need{const n=value as Need;if(!n||typeof n.text!=='string'||n.text.length>2000||!['packaging','office','cleaning'].includes(n.category)||!Number.isInteger(n.quantity)||n.quantity<1||n.quantity>500||!Number.isInteger(n.budget)||n.budget<100||n.budget>10000000||!Number.isInteger(n.delivery)||n.delivery<1||n.delivery>30||typeof n.eco!=='boolean'||!Array.isArray(n.sellers)||n.sellers.length<1||n.sellers.some(x=>!SELLERS.includes(x))||!Number.isInteger(n.maxQuantity)||n.maxQuantity<1||n.maxQuantity>100)throw new DomainError('INVALID_NEED','Check quantity, budget, delivery days and at least one approved seller.',400);return {...n,text:n.text.trim()}}
export function invalidate(s:Workspace,reason:string){if(s.approval){audit(s,'Approval invalidated',reason);s.approval=null;}s.order=null;s.lastReceipt=null;}
export function editNeed(s:Workspace,value:unknown){s.need=validateNeed(value);invalidate(s,'The purchase request or policy changed.');const best=ranked(s)[0];if(best)s.selected=best.product.id;audit(s,'Options compared',`Demo rules ranked ${ranked(s).length} fixture items using total cost, stock, seller, delivery and waste constraints.`)}
export function selectProduct(s:Workspace,id:string){if(!s.catalog.some(p=>p.id===id&&p.category===s.need.category))throw new DomainError('INVALID_PRODUCT','Choose an item in this category.',400);if(s.selected!==id)invalidate(s,'A different item was selected.');s.selected=id;audit(s,'Proposal edited',`Selected ${s.catalog.find(p=>p.id===id)?.name}.`)}
export async function approve(s:Workspace,expectedFingerprint?:string){if(expectedFingerprint&&expectedFingerprint!==await fingerprint(currentQuote(s)))throw new DomainError('STALE_REVIEW','The displayed quote changed. Refresh, review the new details and approve again.');const p=s.catalog.find(p=>p.id===s.selected)!;const problems=violations(p,s.need);if(problems.length)throw new DomainError('POLICY_BLOCKED',problems.join(' · '));const quote=currentQuote(s);const now=Date.now();s.approval={id:crypto.randomUUID(),fingerprint:await fingerprint(quote),quote,createdAt:new Date(now).toISOString(),expiresAt:new Date(now+15*60*1000).toISOString()};s.order=null;s.lastReceipt=null;audit(s,'Exact proposal approved',`${money(quote.total)} USD, ${s.need.quantity} × ${p.name}. Approval expires in 15 minutes.`);return s.approval}
export async function verifyApproval(s:Workspace,id:string,now=Date.now()){const a=s.approval;if(!a||a.id!==id)throw new DomainError('APPROVAL_REQUIRED','Review and approve this exact proposal before checkout.');if(Date.parse(a.expiresAt)<=now)throw new DomainError('APPROVAL_EXPIRED','Approval expired. Review the current quote and approve again.');if(a.fingerprint!==await fingerprint(currentQuote(s)))throw new DomainError('STALE_APPROVAL','Price, stock or delivery changed. Review the new quote and approve again.');const problems=violations(s.catalog.find(p=>p.id===s.selected)!,s.need);if(problems.length)throw new DomainError('POLICY_BLOCKED',problems.join(' · '));return a}
export function mutateCatalog(s:Workspace,kind:'price'|'stock'){const p=s.catalog.find(p=>p.id===s.selected)!;if(kind==='price')p.price+=250;else p.stock=Math.max(0,s.need.quantity-1);p.revision++;audit(s,kind==='price'?'Price changed':'Stock changed',`${p.name}: ${kind==='price'?money(p.price)+' per pack':p.stock+' packs available'}. Existing approval cannot be used.`)}
export async function simulatedCheckout(s:Workspace,approvalId:string){const prior=s.receipts.find(r=>r.approvalId===approvalId);if(prior){audit(s,'Duplicate prevented',`Reused receipt ${prior.id}. No second order was created.`);s.lastReceipt=prior.id;return {receipt:prior,replayed:true}}const a=await verifyApproval(s,approvalId);const receipt:Receipt={id:'SP-'+crypto.randomUUID().slice(0,8).toUpperCase(),approvalId,quote:a.quote,createdAt:new Date().toISOString(),mode:'demo',orderId:'DEMO-'+approvalId.slice(0,8),captureId:'SIMULATED-'+approvalId.slice(0,8)};s.receipts.unshift(receipt);s.lastReceipt=receipt.id;s.catalog.find(p=>p.id===s.selected)!.stock-=s.need.quantity;audit(s,'Demo checkout completed',`${receipt.id} · ${money(receipt.quote.total)} USD. Simulation only; no payment or fulfilment.`);return {receipt,replayed:false}}
