import type { Quote } from './domain.ts';
export type PayPalConfig={PAYPAL_CLIENT_ID?:string;PAYPAL_CLIENT_SECRET?:string;PAYPAL_MODE?:string};
export type PayPalOrder={id:string;status:string;links?:{rel:string;href:string}[];purchase_units?:{amount?:{currency_code:string;value:string};payments?:{captures?:{id:string;status:string;amount:{currency_code:string;value:string}}[]}}[]};
const BASE='https://api-m.sandbox.paypal.com';
export function configured(e:PayPalConfig){return e.PAYPAL_MODE==='sandbox'&&Boolean(e.PAYPAL_CLIENT_ID&&e.PAYPAL_CLIENT_SECRET)}
export function buildOrder(quote:Quote,approvalId:string,origin:string){return {intent:'CAPTURE',purchase_units:[{reference_id:approvalId,custom_id:approvalId,description:'SupplyPilot demo merchant supply order',items:quote.lines.map(l=>({name:l.name,sku:l.productId,quantity:String(l.quantity),unit_amount:{currency_code:'USD',value:(l.unitPrice/100).toFixed(2)}})),amount:{currency_code:'USD',value:(quote.total/100).toFixed(2),breakdown:{item_total:{currency_code:'USD',value:(quote.subtotal/100).toFixed(2)},shipping:{currency_code:'USD',value:(quote.shipping/100).toFixed(2)},tax_total:{currency_code:'USD',value:(quote.tax/100).toFixed(2)}}}}],payment_source:{paypal:{experience_context:{brand_name:'SupplyPilot Sandbox',user_action:'PAY_NOW',shipping_preference:'NO_SHIPPING',return_url:origin+'/app?paypal=return',cancel_url:origin+'/app?paypal=cancel'}}}}}
export class PayPalSandbox {
 constructor(private config:PayPalConfig,private transport:typeof fetch=fetch){}
 private async request(path:string,method='GET',body?:unknown,key?:string):Promise<PayPalOrder>{if(!configured(this.config))throw new Error('PayPal sandbox is not configured. Use the simulator or add server-side sandbox credentials.');const tokenResponse=await this.transport(BASE+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+btoa(this.config.PAYPAL_CLIENT_ID+':'+this.config.PAYPAL_CLIENT_SECRET),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!tokenResponse.ok)throw new Error('PayPal sandbox authentication failed. Check server-side configuration.');const token=await tokenResponse.json() as {access_token:string};const response=await this.transport(BASE+path,{method,headers:{Authorization:'Bearer '+token.access_token,'Content-Type':'application/json',...(key?{'PayPal-Request-Id':key}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(`PayPal sandbox returned HTTP ${response.status}. Retry the same action; the request ID is preserved.`);return await response.json() as PayPalOrder}
 create(quote:Quote,approvalId:string,origin:string,key:string){return this.request('/v2/checkout/orders','POST',buildOrder(quote,approvalId,origin),key)}
 capture(orderId:string,key:string){if(!/^[A-Z0-9-]{4,40}$/i.test(orderId))throw new Error('Invalid PayPal order ID');return this.request('/v2/checkout/orders/'+encodeURIComponent(orderId)+'/capture','POST',{},key)}
 status(orderId:string){if(!/^[A-Z0-9-]{4,40}$/i.test(orderId))throw new Error('Invalid PayPal order ID');return this.request('/v2/checkout/orders/'+encodeURIComponent(orderId))}
}
export function verifiedCapture(order:PayPalOrder,quote:Quote){const captures=order.purchase_units?.flatMap(p=>p.payments?.captures??[])??[];const completed=captures.filter(c=>c.status==='COMPLETED');if(order.status!=='COMPLETED'||completed.length!==1||completed[0].amount.currency_code!==quote.currency||completed[0].amount.value!==(quote.total/100).toFixed(2))throw new Error('Capture is not a completed payment for the exact approved total. Reconcile the same order before retrying.');return completed[0]}
