import {readWorkspace,saveWorkspace,type RuntimeEnv} from '../lib/procurement/store.ts';
import {initialWorkspace,editNeed,selectProduct,approve,mutateCatalog,simulatedCheckout,currentQuote,fingerprint,DomainError,audit,ranked,verifyApproval,type Receipt} from '../lib/procurement/domain.ts';
import {configured,PayPalSandbox,verifiedCapture} from '../lib/procurement/paypal.ts';
import {explainWithProvider} from '../lib/procurement/ai.ts';
import {aiConfigured} from '../lib/procurement/ai-provider.mjs';
declare const PAGE_HTML:string;
function response(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
async function payload(env:RuntimeEnv){const {state,version}=await readWorkspace(env);const stale=state.approval?state.approval.fingerprint!==await fingerprint(currentQuote(state))||Date.parse(state.approval.expiresAt)<=Date.now():false;return {state,version,stale,quoteFingerprint:await fingerprint(currentQuote(state)),config:{paypal:configured(env),ai:aiConfigured(env)}}}
async function workspace(request:Request,env:RuntimeEnv){if(request.method==='GET')return response(await payload(env));const body=await request.json() as {action:string;need?:unknown;productId?:string;approvalId?:string;loseResponse?:boolean;expectedVersion?:number;expectedFingerprint?:string};const {state,version}=await readWorkspace(env);if(state.order&&body.action!=='explain')throw new DomainError('ACTIVE_CHECKOUT','Finish or reconcile the existing PayPal sandbox attempt before changing this request.');let replayed=false;switch(body.action){case 'compare':editNeed(state,body.need);break;case 'select':selectProduct(state,body.productId??'');break;case 'approve':if(body.expectedVersion!==version||!body.expectedFingerprint)throw new DomainError('STALE_REVIEW','The workspace changed since you reviewed it. Refresh and review the quote again.');await approve(state,body.expectedFingerprint);break;case 'price':case 'stock':mutateCatalog(state,body.action);break;case 'checkout':{const result=await simulatedCheckout(state,body.approvalId??'');replayed=result.replayed;if(body.loseResponse&&!state.lostResponses.includes(body.approvalId??'')){state.lostResponses.push(body.approvalId!);audit(state,'Response interrupted','Demo receipt was committed, but the first response was intentionally dropped. Retry uses the same approval ID.');await saveWorkspace(env,state,version);return response({error:'Demo connection interrupted after processing. Retry checkout to recover the same receipt.',code:'SIMULATED_TIMEOUT'},503)}break;}case 'reset':{const fresh=initialWorkspace();fresh.receipts=state.receipts;fresh.audit=state.audit;audit(fresh,'Request reset','Fixture inventory and purchasing request restored. Prior receipts and audit history kept.');await saveWorkspace(env,fresh,version);return response(await payload(env));}case 'explain':{if(!aiConfigured(env))throw new DomainError('AI_UNCONFIGURED','This demo uses transparent ranking rules. The optional AI provider is not connected.',400);const explanation=await explainWithProvider(state.need,ranked(state).map(x=>x.product),env);return response({...await payload(env),explanation:explanation.text,aiSource:explanation.engine,aiWarning:explanation.warning});}default:throw new DomainError('INVALID_ACTION','Unknown action.',400)}await saveWorkspace(env,state,version);return response({...await payload(env),replayed})}
async function paypal(request:Request,env:RuntimeEnv){if(!configured(env))throw new DomainError('PAYPAL_UNCONFIGURED','PayPal sandbox is not connected. Server-side sandbox credentials are required.',503);const body=await request.json() as {action:'create'|'capture'|'status'|'abandon';approvalId:string};if(!['create','capture','status','abandon'].includes(body.action))throw new DomainError('INVALID_ACTION','Unknown PayPal action.',400);const {state,version}=await readWorkspace(env);const prior=state.receipts.find(r=>r.approvalId===body.approvalId);if(prior)return response({receipt:prior,replayed:true});
// Read-only reconciliation remains allowed after approval expiry. It cannot create or capture money.
const attempt=state.order;const approval=['status','abandon'].includes(body.action)?state.approval:await verifyApproval(state,body.approvalId);if(!approval||approval.id!==body.approvalId)throw new DomainError('APPROVAL_REQUIRED','The checkout approval is missing.');const adapter=new PayPalSandbox(env);
if(body.action==='create'){
 if(attempt?.approvalId===approval.id&&attempt.id)return response({order:attempt});
 if(!state.order){state.order={approvalId:approval.id,id:null,createKey:crypto.randomUUID(),captureKey:crypto.randomUUID(),startedAt:new Date().toISOString()};await saveWorkspace(env,state,version)}
 const active=state.order;if(active.approvalId!==approval.id)throw new DomainError('ORDER_MISMATCH','Reconcile the existing checkout first.');
 if(Date.now()-Date.parse(active.startedAt)>5*60*60*1000)throw new DomainError('RECONCILE_REQUIRED','This uncertain attempt is too old to retry safely. Reconcile it in the PayPal sandbox before resetting.');
 const remote=await adapter.create(approval.quote,approval.id,new URL(request.url).origin,active.createKey);const latest=await readWorkspace(env);if(latest.state.order?.createKey!==active.createKey)throw new DomainError('CHECKOUT_CHANGED','Checkout changed while creating the order. Reconcile the sandbox before retrying.');latest.state.order.id=remote.id;const url=remote.links?.find(l=>l.rel==='payer-action'||l.rel==='approve')?.href;if(url&&new URL(url).hostname==='www.sandbox.paypal.com')latest.state.order.approveUrl=url;audit(latest.state,'PayPal sandbox order created',remote.id+' · awaiting buyer approval in the PayPal sandbox.');await saveWorkspace(env,latest.state,latest.version);return response({order:latest.state.order});
}
 if(!attempt?.id||attempt.approvalId!==approval.id)throw new DomainError('ORDER_REQUIRED','Create a sandbox order first.');
 if(body.action==='capture'&&!attempt.captureStartedAt){attempt.captureStartedAt=new Date().toISOString();await saveWorkspace(env,state,version)}
 const remote=body.action==='capture'?await adapter.capture(attempt.id,attempt.captureKey):await adapter.status(attempt.id);
 if(body.action==='abandon'&&remote.status!=='COMPLETED'){if(attempt.captureStartedAt||!['CREATED','APPROVED','VOIDED'].includes(remote.status))throw new DomainError('RECONCILE_REQUIRED','This checkout has a capture attempt or uncertain state. Reconcile its status before abandoning.');const latest=await readWorkspace(env);if(latest.state.order?.id!==attempt.id||latest.state.order.captureStartedAt)throw new DomainError('RECONCILE_REQUIRED','Checkout changed while checking its status. Refresh and reconcile again.');latest.state.order=null;latest.state.approval=null;audit(latest.state,'Uncaptured sandbox checkout abandoned',attempt.id+' verified '+remote.status+'. No capture was attempted. Remote order is not cancelled; it can no longer be captured through this app.');await saveWorkspace(env,latest.state,latest.version);return response({abandoned:true,status:remote.status})}
 if(remote.status!=='COMPLETED')return response({status:remote.status,order:attempt});
 const capture=verifiedCapture(remote,approval.quote);const latest=await readWorkspace(env);const priorReceipt=latest.state.receipts.find(r=>r.approvalId===approval.id);if(priorReceipt)return response({receipt:priorReceipt,replayed:true});const receipt:Receipt={id:'SP-'+crypto.randomUUID().slice(0,8).toUpperCase(),approvalId:approval.id,quote:approval.quote,createdAt:new Date().toISOString(),mode:'sandbox',captureId:capture.id,orderId:remote.id};latest.state.receipts.unshift(receipt);latest.state.lastReceipt=receipt.id;latest.state.order=null;latest.state.catalog.find(p=>p.id===latest.state.selected)!.stock-=latest.state.need.quantity;audit(latest.state,'PayPal sandbox capture reconciled',remote.id+' · '+capture.id+' · exact amount verified.');await saveWorkspace(env,latest.state,latest.version);return response({receipt});
}
export default {async fetch(request:Request,env:RuntimeEnv){try{const url=new URL(request.url);if(url.pathname==='/api/health')return response({ok:true,app:'SupplyPilot',paymentMode:configured(env)?'sandbox':'demo'});if(url.pathname.startsWith('/api/')){if(!['GET','POST'].includes(request.method))return response({error:'Method not allowed'},405);if(request.method==='POST'){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return response({error:'Cross-origin request blocked'},403);const length=Number(request.headers.get('content-length')??'0');if(length>16000)return response({error:'Request too large'},413)}if(url.pathname==='/api/workspace')return await workspace(request,env);if(url.pathname==='/api/paypal'&&request.method==='POST')return await paypal(request,env);return response({error:'Not found'},404)}if(url.pathname!=='/')return new Response('Not found',{status:404});return new Response(PAGE_HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'self'; base-uri 'none'; form-action 'self'"}})}catch(e){console.error('procurement',e instanceof DomainError?e.code:e instanceof Error?e.message:'unknown');return response({error:e instanceof Error?e.message:'Could not complete the request. Your input is preserved.',code:e instanceof DomainError?e.code:'UNAVAILABLE'},e instanceof DomainError?e.status:500)}}};
